repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-merge-conflict
      - id: trailing-whitespace
  - repo: https://github.com/tdeo/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: rubocop
        name: Rubocop
        language: system
        entry: bin/rubocop
        require_serial: true # for proper cache behavior
        files: (?x)(
          \.rb|
          \.rake|
          \.gemspec|
          Gemfile|
          Rakefile)$
        args:
          - --autocorrect
          - --server
          - --fail-level=convention
