name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1.196.0
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Setup pre-commit and run linters
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: bin/rspec
