name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - gemfiles/rails_7_2.gemfile
          - gemfiles/rails_8_0.gemfile
          - gemfiles/rails_8_1.gemfile
          - gemfiles/rails_edge.gemfile
    continue-on-error: ${{ matrix.gemfile == 'gemfiles/rails_edge.gemfile' }}

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.1
          bundler-cache: true

      - name: Setup pre-commit and run linters
        uses: pre-commit/action@v3.0.1

      - name: Run tests
        run: bin/rspec

  test:
    name: All required tests passed
    needs: matrix-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check status
        run: |
          if [ "${{ needs.test.result }}" == "success" ] || [ "${{ needs.test.result }}" == "skipped" ]; then
            echo "All required tests passed!"
            exit 0
          else
            echo "Required tests failed."
            exit 1
          fi