name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.196.0
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Install pre-commit
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends python3 python3-pip
          pip install pre-commit --break-system-packages
          pre-commit install --install-hooks

      - name: Run linters
        run: pre-commit run --all-files

      - name: Run tests
        run: bin/rspec
