name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.196.0
        with:
          ruby-version: 3.3.4

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bin/rspec

      - name: Run linters
        run: pre-commit run --all-files
